module BuildingColors
  COLORS = {
    Color::BLACK => [
      Color::LIGHT_GRAY,
      Color::MEDIUM_BLUE,
      Color::DARK_PINK,
      Color::PINK,
      Color::RED,
      Color::WHITE,
      Color::YELLOW,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::BLUE => [
      Color::WHITE,
      Color::YELLOW,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::BRIGHT_GREEN => [
      Color::WHITE,
      Color::YELLOW,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::DARK_BLUISH_GRAY => [
      Color::WHITE,
      Color::YELLOW,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::DARK_TURQUOISE => [
      Color::WHITE,
      Color::YELLOW,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::GREEN => [
      Color::WHITE,
      Color::YELLOW,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::LIGHT_GRAY => [
      Color::BLACK,
      Color::BLUE,
      Color::BRIGHT_GREEN,
      Color::DARK_BLUISH_GRAY,
      Color::DARK_TURQUOISE,
      Color::GREEN,
      Color::MEDIUM_BLUE,
      Color::PINK,
      Color::RED,
      Color::YELLOW,
      Color::DARK_PINK,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::MEDIUM_BLUE => [
      Color::BLACK,
      Color::BLUE,
      Color::BRIGHT_GREEN,
      Color::DARK_BLUISH_GRAY,
      Color::DARK_TURQUOISE,
      Color::GREEN,
      Color::LIGHT_GRAY,
      Color::PINK,
      Color::RED,
      Color::WHITE,
      Color::YELLOW,
      Color::DARK_PINK,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::PINK => [
      Color::BLACK,
      Color::BLUE,
      Color::BRIGHT_GREEN,
      Color::DARK_BLUISH_GRAY,
      Color::DARK_TURQUOISE,
      Color::GREEN,
      Color::LIGHT_GRAY,
      Color::MEDIUM_BLUE,
      Color::RED,
      Color::WHITE,
    ],
    Color::RED => [
      Color::WHITE,
      Color::YELLOW,
    ],
    Color::WHITE => [
      Color::BLACK,
      Color::BLUE,
      Color::BRIGHT_GREEN,
      Color::DARK_BLUISH_GRAY,
      Color::DARK_TURQUOISE,
      Color::GREEN,
      Color::LIGHT_GRAY,
      Color::MEDIUM_BLUE,
      Color::PINK,
      Color::RED,
      Color::DARK_PINK,
      Color::ORANGE,
      Color::LIGHT_FLESH,
    ],
    Color::YELLOW => [
      Color::BLACK,
      Color::BLUE,
      Color::BRIGHT_GREEN,
      Color::DARK_BLUISH_GRAY,
      Color::DARK_TURQUOISE,
      Color::GREEN,
      Color::LIGHT_GRAY,
      Color::MEDIUM_BLUE,
      Color::RED,
      Color::WHITE,
      Color::ORANGE,
    ],
    Color::DARK_PINK => [
      Color::BLACK,
      Color::BLUE,
      Color::BRIGHT_GREEN,
      Color::DARK_BLUISH_GRAY,
      Color::DARK_TURQUOISE,
      Color::GREEN,
      Color::LIGHT_GRAY,
      Color::MEDIUM_BLUE,
      Color::RED,
      Color::WHITE,
      Color::YELLOW,
      Color::ORANGE,
    ],
    Color::ORANGE => [
      Color::BLACK,
      Color::BLUE,
      Color::BRIGHT_GREEN,
      Color::DARK_BLUISH_GRAY,
      Color::DARK_TURQUOISE,
      Color::GREEN,
      Color::LIGHT_GRAY,
      Color::MEDIUM_BLUE,
      Color::RED,
      Color::WHITE,
      Color::YELLOW,
      Color::LIGHT_FLESH,
    ],
    Color::LIGHT_FLESH => [
      Color::BLACK,
      Color::BLUE,
      Color::BRIGHT_GREEN,
      Color::DARK_BLUISH_GRAY,
      Color::DARK_PINK,
      Color::DARK_TURQUOISE,
      Color::GREEN,
      Color::LIGHT_GRAY,
      Color::MEDIUM_BLUE,
      Color::ORANGE,
      Color::PINK,
      Color::RED,
      Color::WHITE,
      Color::YELLOW,
    ],
  }.freeze

end